
name: main
on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: '16'
         cache: 'npm'

     - name: Setup
       run: make setup
     - name: Test
       run: make test
     - name: Lint
       run: make lint
     - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}