
name: main
on:
  - push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: setup node
        with:
          node-version: "16"

      - name: setup project
        run: make setup

      - name: test
        run: make test

      - name: linter
        run: make lint

