name: hexlet-ci-app
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
      steps:
      - run: make install
      - run: make build
      - run: make start
      - run: make test
      - run: make lint